spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/style_stack_qa
    username: stylestack_qa_user
    password: QaPassword@123

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true