
spring:
  application:
    name: style-stack-app

  profiles:
    active: dev

  jackson:
    default-property-inclusion: non_null

server:
  port: 8081

jwt:
  secret: 4rK7xP9mQ2vN8sT5wY1cE6fH3jL0zA4bK7xP9mQ2vN8sT5wY1cE6fH3jL0zA4
  expiration: 900000
  refresh-expiration: 604800000

profiles:
  active: dev
